# -*- coding: utf-8 -*-
"""PilotNavigationSystem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jm9xE0dYNT4znPub6S6tzsd8sffaxfTt
"""

#Plane Navigation System

Altitude=int(input("Please Enter The Altitude:"))
if Altitude<=3000:
  print("The Plane Is Safe For Landing.")
elif 3000<Altitude<6000:
  print("For Safe Landing Of The Plane You Need To Attain The Altitude Of 3000ft Or Lower But You Can Try To Land At This Altitude.")
else:
  print("Danger :Out Of Altitude Range. You Cannot Land The Plane At This Altitude. Please Go Around Until You Reach To Safer Altitude Range(<=3000) ")